const LOG_ACTIONS = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED',
  USER_ADDRESS_UPDATED: 'USER_ADDRESS_UPDATED',
  FIT_PROFILE_UPDATED: 'FIT_PROFILE_UPDATED',
  PLAN_VIEWED: 'PLAN_VIEWED',
  PLAN_CREATED: 'PLAN_CREATED',
  PLAN_UPDATED: 'PLAN_UPDATED',
  SUBSCRIPTION_CREATED: 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_PAUSED: 'SUBSCRIPTION_PAUSED',
  SUBSCRIPTION_RESUMED: 'SUBSCRIPTION_RESUMED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_UPDATED: 'SUBSCRIPTION_UPDATED',
  SUBSCRIPTION_FAILED: 'SUBSCRIPTION_FAILED',
  CATALOG_SEEDED: 'CATALOG_SEEDED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTH_ERROR: 'AUTH_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};

module.exports = { LOG_ACTIONS };
